In [141]:
import pandas as pd
import seaborn as sns
import matplotlib.pyplot as plt

df = sns.load_dataset('titanic')
df.head(5)

,survived,pclass,sex,age,sibsp,parch,fare,embarked,class,who,adult_male,deck,embark_town,alive,alone
0,0,3,male,22.0,1,0,7.2500,S,Third,man,True,NaN,Southampton,no,False
1,1,1,female,38.0,1,0,71.2833,C,First,woman,False,C,Cherbourg,yes,False
2,1,3,female,26.0,0,0,7.9250,S,Third,woman,False,NaN,Southampton,yes,True
3,1,1,female,35.0,1,0,53.1000,S,First,woman,False,C,Southampton,yes,False
4,0,3,male,35.0,0,0,8.0500,S,Third,man,True,NaN,Southampton,no,True

In [142]:
df.describe()

         survived      pclass         age       sibsp       parch        fare
count  891.000000  891.000000  714.000000  891.000000  891.000000  891.000000
mean     0.383838    2.308642   29.699118    0.523008    0.381594   32.204208
std      0.486592    0.836071   14.526497    1.102743    0.806057   49.693429
min      0.000000    1.000000    0.420000    0.000000    0.000000    0.000000
25%      0.000000    2.000000   20.125000    0.000000    0.000000    7.910400
50%      0.000000    3.000000   28.000000    0.000000    0.000000   14.454200
75%      1.000000    3.000000   38.000000    1.000000    0.000000   31.000000
max      1.000000    3.000000   80.000000    8.000000    6.000000  512.329200

In [143]:
df.drop(['sibsp','parch','embarked','class','adult_male','alive','alone','who','embark_town'], axis=1, inplace=True)
df.head(5)

   survived  pclass     sex   age     fare deck
0         0       3    male  22.0   7.2500  NaN
1         1       1  female  38.0  71.2833    C
2         1       3  female  26.0   7.9250  NaN
3         1       1  female  35.0  53.1000    C
4         0       3    male  35.0   8.0500  NaN

In [144]:
df.describe()

         survived      pclass         age        fare
count  891.000000  891.000000  714.000000  891.000000
mean     0.383838    2.308642   29.699118   32.204208
std      0.486592    0.836071   14.526497   49.693429
min      0.000000    1.000000    0.420000    0.000000
25%      0.000000    2.000000   20.125000    7.910400
50%      0.000000    3.000000   28.000000   14.454200
75%      1.000000    3.000000   38.000000   31.000000
max      1.000000    3.000000   80.000000  512.329200

In [145]:
y = df.survived

In [146]:
y

0      0
1      1
2      1
3      1
4      0
      ..
886    0
887    1
888    0
889    1
890    0
Name: survived, Length: 891, dtype: int64

In [147]:
X = df.iloc[:, 1:]

In [148]:
X

     pclass     sex   age     fare deck
0         3    male  22.0   7.2500  NaN
1         1  female  38.0  71.2833    C
2         3  female  26.0   7.9250  NaN
3         1  female  35.0  53.1000    C
4         3    male  35.0   8.0500  NaN
..      ...     ...   ...      ...  ...
886       2    male  27.0  13.0000  NaN
887       1  female  19.0  30.0000    B
888       3  female   NaN  23.4500  NaN
889       1    male  26.0  30.0000    C
890       3    male  32.0   7.7500  NaN

[891 rows x 5 columns]

In [149]:
dummies = pd.get_dummies(X.sex)
dummies.head(4)

   female   male
0   False   True
1    True  False
2    True  False
3    True  False

In [150]:
X = pd.concat([X, dummies], axis=1)
X.head(3)

   pclass     sex   age     fare deck  female   male
0       3    male  22.0   7.2500  NaN   False   True
1       1  female  38.0  71.2833    C    True  False
2       3  female  26.0   7.9250  NaN    True  False

In [151]:
X.drop(['sex', 'deck'], axis=1, inplace=True)

In [152]:
X.head(5)

   pclass   age     fare  female   male
0       3  22.0   7.2500   False   True
1       1  38.0  71.2833    True  False
2       3  26.0   7.9250    True  False
3       1  35.0  53.1000    True  False
4       3  35.0   8.0500   False   True

In [153]:
X['age'] = x['age'].fillna(X['age'].mean())

In [154]:
X.describe()

           pclass         age        fare
count  891.000000  891.000000  891.000000
mean     2.308642   29.699118   32.204208
std      0.836071   13.002015   49.693429
min      1.000000    0.420000    0.000000
25%      2.000000   22.000000    7.910400
50%      3.000000   29.699118   14.454200
75%      3.000000   35.000000   31.000000
max      3.000000   80.000000  512.329200

In [155]:
X.head(5)

   pclass   age     fare  female   male
0       3  22.0   7.2500   False   True
1       1  38.0  71.2833    True  False
2       3  26.0   7.9250    True  False
3       1  35.0  53.1000    True  False
4       3  35.0   8.0500   False   True

In [157]:
X["female"] = X["female"].astype(int)

In [158]:
X["male"] = X['male'].astype(int)

In [159]:
X.head(5)

   pclass   age     fare  female  male
0       3  22.0   7.2500       0     1
1       1  38.0  71.2833       1     0
2       3  26.0   7.9250       1     0
3       1  35.0  53.1000       1     0
4       3  35.0   8.0500       0     1

In [160]:
from sklearn.model_selection import train_test_split

X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.3, random_state=42)

In [161]:
X_train.shape

(623, 5)

In [163]:
y_train.shape

(623,)

In [164]:
from sklearn.naive_bayes import GaussianNB
model = GaussianNB()

In [168]:
model.fit(X_train, y_train)

GaussianNB()

In [169]:
model.score(X_test, y_test)

0.7873134328358209

In [170]:
X_test[:10]

     pclass        age     fare  female  male
709       3  29.699118  15.2458       0     1
439       2  31.000000  10.5000       0     1
840       3  20.000000   7.9250       0     1
720       2   6.000000  33.0000       1     0
39        3  14.000000  11.2417       1     0
290       1  26.000000  78.8500       1     0
300       3  29.699118   7.7500       1     0
333       3  16.000000  18.0000       0     1
208       3  16.000000   7.7500       1     0
136       1  19.000000  26.2833       1     0

In [171]:
y_test[:10]

709    1
439    0
840    0
720    1
39     1
290    1
300    1
333    0
208    1
136    1
Name: survived, dtype: int64

In [175]:
y_pred = model.predict(X_test[:10])

In [176]:
y_pred

array([0, 0, 0, 1, 1, 1, 1, 0, 1, 1])